---
# Looping through hash from default vars. The loop syntax comes from examples at the following link:
# https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/repository_set_module.html#examples
- name: "Enable Red Hat Repos for ORG2"
  theforeman.foreman.repository_set:
    organization: "ORG2"
    label: "{{ item.label }}"
    repositories: "{{ item.repositories | default(omit) }}"
    all_repositories: "{{ item.repositories is not defined }}"
    state: enabled
    validate_certs: no
  delegate_to: localhost
  loop: "{{ redhat_repos_for_org2 }}"
  tags:
    - repos
